worlds:
    test 1.13a:
    - FLGY967P4
    - F1B6QWAYK
    - NHIDW8U2S
    - 5PETBFDHE
    - 3LKEQD55J
    - XTXFDMKSF
    - 0PQKVXPFL
    - JAPLM621V
    - 22LL1P0WG
    - 2VTURPIOB
    - I70QNSWBF
    - DGYONG2AY
    test 2 1.14a - islands:
    - 62RMXQBZF
    - 0AHGUHWCI
    - L3OELMQ65
    - CMUPITHQX
    - 76BN6SOFT
    - OBBO8MOP8
    - V1DP7ZJXF
    - 6J9OAKR02
    test 1.15 - continents:
    - BFGM1JKFM
    - EGTXMS9VB
    - U8T0V7W3F
    - HK5UKJA24
    - MIE8KGC68
    - C1F9PWBO0
    - Z267WTQCZ
    - 25MCFNJH8
    - 25MIXB1A6
    - FU51R2QFD
    - AXVGARWU6
    - GFKEVJE0X
    - E3QX6KF7N
    1.16-2 continents:
    - I0C6IW0SR
    - AAY9TTLOQ
    corath:
    - 84P16E34W
    - I545QTEJK
    - 85TMOAFOZ
    - 1FDBTM57X
    alkor:
    - J8XWN8ZQ1
    alkor-beta:
    - ZFDYAMIBI
    alkor-charlie:
    - FFOELAW6O
    new world:
    - C8E1IQRQN
    - ZEJHTHSEP
    - QBHV9GBGR
    pavla:
    - CHABWH85Y
    coralis:
    - FFUHC5IWK
    - 0VBV88U2S
    - Y0FQZY730
    cralis iv:
    - ZFG8AD4E2
